// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClfK68BglKOqGWnSNjtWo8PQncMI90UI0',
    appId: '1:654585260888:web:a6d7159f22ca2a49fb132d',
    messagingSenderId: '654585260888',
    projectId: 'task-managment-a4ed2',
    authDomain: 'task-managment-a4ed2.firebaseapp.com',
    storageBucket: 'task-managment-a4ed2.firebasestorage.app',
    measurementId: 'G-9PZ0SHL90J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkUGwKK6T0tH0YPqQMQEbe6TX3z7yA6U0',
    appId: '1:654585260888:android:970fd106e7118366fb132d',
    messagingSenderId: '654585260888',
    projectId: 'task-managment-a4ed2',
    storageBucket: 'task-managment-a4ed2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO4yB3nDRbOvXLcT51IuWKtusJ7el1Z5A',
    appId: '1:654585260888:ios:c9614308b908b185fb132d',
    messagingSenderId: '654585260888',
    projectId: 'task-managment-a4ed2',
    storageBucket: 'task-managment-a4ed2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO4yB3nDRbOvXLcT51IuWKtusJ7el1Z5A',
    appId: '1:654585260888:ios:c9614308b908b185fb132d',
    messagingSenderId: '654585260888',
    projectId: 'task-managment-a4ed2',
    storageBucket: 'task-managment-a4ed2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
